apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sharing
  namespace: jupyterhub
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem
